allowBuilds:
  bigint-buffer: true
  bufferutil: true
  keccak: true
  secp256k1: true
  unrs-resolver: true
  utf-8-validate: true
  yarn: true
onlyBuiltDependencies:
  - bigint-buffer
  - bufferutil
  - keccak
  - secp256k1
  - unrs-resolver
  - utf-8-validate
  - yarn
